---
- name: Creare e configurare container con SSH attivo
  hosts: localhost
  become: yes
  tasks:

    - name: Costruire il container Ubuntu
      docker_image:
        source: build
        build:
          path: ./ubuntu-dockerfile
        name: ubuntu-ssh-container
        tag: latest

    - name: Eseguire il container Ubuntu
      docker_container:
        name: ubuntu-ssh-container
        image: ubuntu-ssh-container:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "22:22"  # Esponiamo la porta 22 per SSH dal Mac
        networks:
          - name: bridge
