---
- name: Creare e configurare container con SSH attivo
  hosts: localhost
  become: yes
  tasks:

    - name: Costruire il container Rocky Linux
      docker_image:
        source: build
        build:
          path: ./rockylinux-dockerfile
        name: rockylinux-ssh-container
        tag: latest

    - name: Eseguire il container Rocky Linux
      docker_container:
        name: rockylinux-ssh-container
        image: rockylinux-ssh-container:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "2222:22"  # Mappiamo la porta 2222 per Rocky Linux per SSH dal Mac
        networks:
          - name: bridge
