---
- name: Esecuzione del setup completo
  hosts: localhost
  become: yes
  vars:
    ubuntu_dockerfile_path: ./ubuntu-dockerfile
    rockylinux_dockerfile_path: ./rockylinux-dockerfile

  roles:
    - role: registry
    - role: build_images
    - role: run_containers
