---
- name: Verificare se Docker è installato
  command: which docker
  register: docker_check
  ignore_errors: yes

- name: Verificare se Podman è installato
  command: which podman
  register: podman_check
  ignore_errors: yes

- name: Imposta il motore dei container
  set_fact:
    container_engine: >
      {% if docker_check.rc == 0 %} docker
      {% elif podman_check.rc == 0 %} podman
      {% else %} none {% endif %}

- name: Normalizza il valore di container_engine
  set_fact:
    container_engine: "{{ container_engine | trim }}"

- name: Debug container_engine
  debug:
    msg: "Il motore selezionato è: {{ container_engine }}"

- name: Fallire se nessun motore di container è disponibile
  fail:
    msg: "Né Docker né Podman sono installati!"
  when: container_engine == "none"

- name: Costruire immagine Ubuntu con Docker
  docker_image:
    source: build
    build:
      path: "./ubuntu-dockerfile"
    name: ubuntu-ssh-container
    tag: latest
  when: container_engine == "docker"

- name: Costruire immagine Rocky Linux con Docker
  docker_image:
    source: build
    build:
      path: "./rockylinux-dockerfile"
    name: rockylinux-ssh-container
    tag: latest
  when: container_engine == "docker"

- name: Costruire immagine Ubuntu con Podman
  command: >
    podman build --tag ubuntu-ssh-container:latest ./ubuntu-dockerfile
  args:
    warn: false
  when: container_engine == "podman"

- name: Costruire immagine Rocky Linux con Podman
  command: >
    podman build --tag rockylinux-ssh-container:latest ./rockylinux-dockerfile
  args:
    warn: false
  when: container_engine == "podman"
